---
- name: "Enable {{ service }} rich rule ({{ rate_limit }}{% if family is defined %}, {{ family }}{% endif %})" # noqa no-changed-when
  shell:
    cmd: "firewall-cmd --permanent --add-rich-rule 'rule{% if family is defined %} family=\"{{ family }}\"{% endif %} service name=\"{{ service }}\" accept limit value=\"{{ rate_limit }}\"'{% if zone is defined %} --zone={{ zone }}{% endif %} && firewall-cmd --reload"
  when: fw_rr_exact_enabled.rc != 0
