---
- include_tasks: new_service.yml

- name: "Check if {{ service }} service is currently enabled"
  command:
    cmd: "firewall-cmd --query-service={{ service }}{% if zone is defined %} --zone={{ zone }}{% endif %}"
  changed_when: false
  failed_when: false
  register: fw_svc_enabled

- name: "Check if any {{ service }} rich rule is currently enabled"
  shell:
    cmd: "firewall-cmd --list-rich-rules{% if zone is defined %} --zone={{ zone }}{% endif %} | grep 'service name=\"{{ service }}\"'"
  changed_when: false
  failed_when: false
  register: fw_rr_any_enabled

- include_tasks: service_plain.yml
  when: rate_limit is not defined

- include_tasks: service_richrule.yml
  when: rate_limit is defined
