---
name: Ubuntu 20.04

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - master
  pull_request:
    branches: []

jobs:
  ubuntu-2004:
    runs-on: ubuntu-latest
    steps:
      - name: Obtain sources
        uses: actions/checkout@v3
      - name: Test Galaxy role
        run: >
            CONT_ID=$(docker run --rm -v ${{ github.workspace }}:/repo -v /sys/fs/cgroup:/sys/fs/cgroup:ro --tmpfs /tmp --tmpfs /run --privileged --detach geerlingguy/docker-ubuntu2004-ansible:latest) &&
            docker exec ${CONT_ID} /bin/bash -c
            "cd /repo &&
            apt -y update &&
            if [ -f requirements.yml ]; then ansible-galaxy role install --force -r requirements.yml; fi &&
            ANSIBLE_ROLES_PATH=.. ANSIBLE_FORCE_COLOR=true ansible-playbook tests/main.yml" &&
            docker stop ${CONT_ID}
